category/urls.py
from django.urls import path
from . import views

app_name = 'category'

urlpatterns = [
    path('', views.index, name='index'),
]

eventcatalog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'eventcatalog'

urlpatterns = [
    path('', views.index, name="index"),
    path('new', views.new, name="new"),
    path('view/<int:id>', views.view, name="view"),
    path('join/<int:id>', views.join, name="join")
]

mainpage/urls.py
from django.urls import path
from . import views

app_name = 'mainpage'

urlpatterns = [
    path('', views.index, name='index'),
]

tk1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('mainpage.urls'), name="mainpage"),
    path('admin/', admin.site.urls),
    path('account/', include('userauth.urls'), name="auth"),
    path('events/', include('eventcatalog.urls'), name="catalog"),
    path('category/', include('category.urls'), name="category"),
]

userauth/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'userauth'

urlpatterns = [
    path('login', auth_views.LoginView.as_view(
        template_name='userauth-login.html', 
        redirect_field_name='mainpage:index', 
        extra_context={'auth': True}
        ), name = 'login'),
    path('register', views.register, name='register'),
    path('logout', views.user_logout, name='logout'),
]

category/models.py
from django.db import models

# Create your models here.

eventcatalog/models.py
from django.db import models

# Create your models here.

mainpage/models.py
from django.db import models

# Create your models here.

userauth/models.py
from django.db import models
from django.contrib.auth.models import User


def get_default_organizer():
    return Organizer.objects.get_or_create(
        user=User.objects.get_or_create(id=1)[0]
        )[0]

# Create your models here.
class Organizer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.user.username

class Event(models.Model):
    nama_event = models.CharField(max_length=30)
    jadwal = models.DateTimeField()
    details = models.TextField(max_length=1000, default="")
    peserta = models.ManyToManyField(User, blank=True)
    penyelenggara = models.ForeignKey(
        Organizer, on_delete=models.CASCADE, default=get_default_organizer)
    
    waktu_dibuat = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.nama_event

eventcatalog/forms.py
from django import forms
from django.utils import timezone
from userauth.models import Event

class EventForm(forms.ModelForm):
    nama_event = forms.CharField(
        widget=forms.TextInput(), 
        max_length=100
    )
    details = forms.CharField(
        widget=forms.Textarea(
            attrs={'placeholder':'informasi detail event'}
            ),
        max_length=1000
    )
    jadwal = forms.DateTimeField(
        widget=forms.TextInput(
            attrs={'type': 'datetime-local'}
        ),
        input_formats=["%m/%d/%Y %H:%M"]
    )
        
    def clean_jadwal(self):
        data = self.cleaned_data["jadwal"]
        if timezone.now() >= data:
            raise forms.ValidationError(u'Tanggal/waktu anda tidak valid!! "%s"' % data)
        return data

    
    class Meta:
        model = Event
        fields = ['nama_event', 'jadwal', 'details']

userauth/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

category/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from userauth.models import Event, Organizer
from django.http import HttpResponse

# Create your views here.
def index(request):
    context = {
        'events': Event.objects.all()
    }
    if request.method == "POST":
        query = request.POST['nama_event']
        context['events'] = context['events'].filter(nama_event__icontains=query)

    return render(request, 'category/category.html', context)

eventcatalog/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from userauth.models import Event, Organizer
from .forms import EventForm

# Create your views here.

def index(request):
    context = {
        'events': Event.objects.all()
    }
    return render(request, 'eventcatalog-index.html', context=context)

@login_required
def new(request):
    context = {}
    if request.method == 'POST':
        form = context['form'] = EventForm(request.POST)
        if form.is_valid():
            event = form.save(commit=False)
            event.penyelenggara, created = Organizer.objects.get_or_create(
                user=request.user
            )
            event.save()
            return redirect('eventcatalog:index')
    
    else:
        context['form'] = EventForm()
        
    return render(request, 'eventcatalog-add.html', context=context)

def view(request, id):
    context = {
        'disable': False
    }
    
    event = Event.objects.get(id=id)
    context['event'] = event
    if request.user in event.peserta.all() or request.user == event.penyelenggara.user:
        context['disable'] = True
    return render(request, 'eventcatalog-view.html', context=context)

@login_required
def join(request, id):
    context = {
        "join": True,
        "disable": True
    }
    event = Event.objects.get(id=id)
    context['event'] = event
    event.peserta.add(request.user)
    context['join_success'] = True
    return render(request, 'eventcatalog-view.html', context=context)

mainpage/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'mainpage-index.html')

userauth/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import  AuthenticationForm
from .forms import CreateUserForm

def register(request):
    context = {
        'auth': True
    }
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        context['form'] = form
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Registrasi berhasil, silahkan login kembali')
            return redirect('userauth:login')

    else:
        context['form'] = CreateUserForm()
        
    return render(request, 'userauth-register.html', context=context)

def user_logout(request):
    logout(request)
    return redirect('userauth:login')

category/templates/category/category.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block head %}
    <title>Temu Categori Detail</title>
{% endblock head %}

{% block style %}
<link rel="stylesheet" href=" {% static 'category/css/bootstrap.min.css' %}" >
<link rel="stylesheet" href=" {% static 'category/fontawesome/css/all.min.css' %}">
<link rel="stylesheet" href=" {% static 'category/css/templatemo-style.css' %}">

<style>
@import url('https://fonts.googleapis.com/css2?family=Lemon&display=swap');
    .navbar-nav > li{
      margin-left: 8px;
      margin-right: 8px;
    }
    
    .navbar-brand {
      font-family: Lemon, cursive;
      font-size: 35px;
      color: #FF6D1C !important;
      text-transform: uppercase;
        text-rendering: optimizeLegibility;
    }    
    body {
        background: linear-gradient(to right, #FEA12E, #F4A77C);
    }

</style>
{% endblock style %}


{% block body %}
{% include 'navigation.html' %}
<!-- Page Loader -->
<div id="loader-wrapper">
    <div id="loader"></div>

    <div class="loader-section section-left"></div>
    <div class="loader-section section-right"></div>

</div>


<!--search bar-->

<div class="tm-hero d-flex justify-content-center align-items-center" data-parallax="scroll">
    <form class="d-flex tm-search-form" action="/category/" method="POST">
        {% csrf_token %}
        <input class="form-control tm-search-input" type="search" placeholder="Search" aria-label="Search" name="nama_event">
        <button class="btn btn-outline-success tm-search-btn" type="submit">
            <i class="fas fa-search"></i>
        </button>
    </form>
</div>






<!--Isi body-->

    <div class="row mb-4">
        <h2 class="col-12 tm-text-primary text-center" style="color: black;">
            Find your Events
        </h2>
        <hr class="bg-dark mb-4 mt-0 d-inline-block mx-auto" style="width: 250px; height: 5px;">
    </div>
    
    <div class="container">
    {% for event in events %}
    <div class="row">
        <div class="col-xl-3 col-lg-4 col-md-6 col-sm-6 col-12 mb-5">
            <div class="card card-signin" style="padding-bottom: 30px;">
                <div class="card-body d-flex flex-column">
                    <h4 class="card-title">{{ event.nama_event }}</h4>
                    <p class="card-subtitle mb-2 text-muted">{{ event.jadwal }}</p>
                    <p class="card-text"> {{ event.details|truncatewords:15 }}</p>
                    <a href={% url 'eventcatalog:view' event.id %} class="mt-auto btn btn-primary btn-lg btn-block" style="margin-top:40px">Read more</a>
                </div>
            </div>
        
        </div>
    </div>
{% endfor %}
</div>
 <!--footer-->
{% include 'footer.html' %}
<!-- row -->   
{% endblock body %}

{% block script_foot %}
<script src=" {% static 'category/js/plugins.js' %}"></script>
<script>
    $(window).on("load", function() {
        $('body').addClass('loaded');
    });
</script>
{% endblock script_foot %}

eventcatalog/templates/eventcatalog-index.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block head %}
<title>TEMU | Events</title>
<meta name="description" content="Discover events around you">

<meta property="og:title" content="TEMU | Events">
<meta property="og:type" content="website">
<meta property="og:site_name" content="TEMU">
{% endblock head %}

{% block script_head %}
<script src="https://kit.fontawesome.com/31c83bd84a.js" crossorigin="anonymous"></script>
{% endblock script_head %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/normalize.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/layout.css' %}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
    integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

<style>
    :root {
        --input-padding-x: 1.5rem;
        --input-padding-y: .75rem;
    }

    body {
        background: linear-gradient(to right, #FEA12E, #F4A77C);
    }

    .row {
        margin-bottom: 2rem;
    }

    .card-deck {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
        grid-gap: .5rem;
    }

    .card-signin {
        border: 0;
        border-radius: 1rem;
        box-shadow: 0 0.5rem 1rem 0 rgba(0, 0, 0, 0.1);
    }

    .card-signin .card-title {
        margin-bottom: 2rem;
        font-weight: 300;
        font-size: 1.5rem;
    }

    .card-signin .card-body {
        padding: 2rem;
    }

    .form-signin {
        width: 100%;
    }

    .form-signin .btn {
        font-size: 80%;
        border-radius: 5rem;
        letter-spacing: .1rem;
        font-weight: bold;
        padding: 1rem;
        transition: all 0.2s;
    }

    .form-label-group {
        position: relative;
        margin-bottom: 1rem;
    }

    .form-label-group input {
        height: auto;
        border-radius: 2rem;
    }

    .form-label-group>input,
    .form-label-group>label {
        padding: var(--input-padding-y) var(--input-padding-x);
    }

    .form-label-group>label {
        position: absolute;
        top: 0;
        left: 0;
        display: block;
        width: 100%;
        margin-bottom: 0;
        /* Override default `<label>` margin */
        line-height: 1.5;
        color: #495057;
        border: 1px solid transparent;
        border-radius: .25rem;
        transition: all .1s ease-in-out;
    }

    .form-label-group input::-webkit-input-placeholder {
        color: transparent;
    }

    .form-label-group input:-ms-input-placeholder {
        color: transparent;
    }

    .form-label-group input::-ms-input-placeholder {
        color: transparent;
    }

    .form-label-group input::-moz-placeholder {
        color: transparent;
    }

    .form-label-group input::placeholder {
        color: transparent;
    }

    .form-label-group input:not(:placeholder-shown) {
        padding-top: calc(var(--input-padding-y) + var(--input-padding-y) * (2 / 3));
        padding-bottom: calc(var(--input-padding-y) / 3);
    }

    .form-label-group input:not(:placeholder-shown)~label {
        padding-top: calc(var(--input-padding-y) / 3);
        padding-bottom: calc(var(--input-padding-y) / 3);
        font-size: 12px;
        color: #777;
    }

    /* Fallback for Edge
-------------------------------------------------- */

    @supports (-ms-ime-align: auto) {
        .form-label-group>label {
            display: none;
        }

        .form-label-group input::-ms-input-placeholder {
            color: #777;
        }
    }

    /* Fallback for IE
-------------------------------------------------- */

    @media all and (-ms-high-contrast: none),
    (-ms-high-contrast: active) {
        .form-label-group>label {
            display: none;
        }

        .form-label-group input:-ms-input-placeholder {
            color: #777;
        }
    }
</style>
{% endblock style %}

{% block body %}
{% include 'navigation.html' %}
<div class="container">
    <div class="jumbotron" style="background-color: transparent; border-bottom: 2px black solid;">
        <h5 class="display-4 text-center">Discover events around you</h5>
    </div>
    <div class="row">
        <div class="card-deck card-columns">
        {% for event in events %}
            <div class="card card-signin">
                <div class="card-body d-flex flex-column">
                    <h4 class="card-title">{{ event.nama_event }}</h4>
                    <p class="card-subtitle mb-2 text-muted">{{ event.jadwal }}</p>
                    <p class="card-text"> {{ event.details|truncatewords:15 }}</p>
                    <a href={% url 'eventcatalog:view' event.id %} class="mt-auto btn btn-primary btn-lg btn-block" style="margin-top:40px">Read more</a>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
    <div class="jumbotron" style="background-color: transparent; border-top: 2px black solid;">
        <h5 class="display-4 text-center">Couldn't find you're looking for?</h5>
        {% comment %} TODO: Implement create new event {% endcomment %}
        <a href={% url 'eventcatalog:new' %} class="btn btn-primary btn-lg btn-block" style="margin-top:40px">Create your own event!</a>
    </div>
    {% endblock body %}

    {% block script_foot %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous">
    </script>
    {% endblock script_foot %}

eventcatalog/templates/eventcatalog-view.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block head %}
<title>TEMU | {{ event.nama_event }}</title>
<meta name="description" content="Discover events around you">

<meta property="og:title" content="TEMU">
<meta property="og:type" content="website">
<meta property="og:site_name" content="TEMU">
{% endblock head %}

{% block script_head %}
<script src="https://kit.fontawesome.com/31c83bd84a.js" crossorigin="anonymous"></script>
{% endblock script_head %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/normalize.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/layout.css' %}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
    integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

<style>
    :root {
        --input-padding-x: 1.5rem;
        --input-padding-y: .75rem;
    }

    body {
        background: linear-gradient(to right, #FEA12E, #F4A77C);
    }

    .card-deck {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
        grid-gap: .5rem;
    }

    .card-signin {
        border: 0;
        border-radius: 1rem;
        box-shadow: 0 0.5rem 1rem 0 rgba(0, 0, 0, 0.1);
    }

    .card-signin .card-title {
        margin-bottom: 2rem;
        font-weight: 300;
        font-size: 1.5rem;
    }

    .card-signin .card-body {
        padding: 2rem;
    }

    .form-signin {
        width: 100%;
    }

    .form-signin .btn {
        font-size: 80%;
        border-radius: 5rem;
        letter-spacing: .1rem;
        font-weight: bold;
        padding: 1rem;
        transition: all 0.2s;
    }

    .form-label-group {
        position: relative;
        margin-bottom: 1rem;
    }

    .form-label-group input {
        height: auto;
        border-radius: 2rem;
    }

    .form-label-group>input,
    .form-label-group>label {
        padding: var(--input-padding-y) var(--input-padding-x);
    }

    .form-label-group>label {
        position: absolute;
        top: 0;
        left: 0;
        display: block;
        width: 100%;
        margin-bottom: 0;
        /* Override default `<label>` margin */
        line-height: 1.5;
        color: #495057;
        border: 1px solid transparent;
        border-radius: .25rem;
        transition: all .1s ease-in-out;
    }

    .form-label-group input::-webkit-input-placeholder {
        color: transparent;
    }

    .form-label-group input:-ms-input-placeholder {
        color: transparent;
    }

    .form-label-group input::-ms-input-placeholder {
        color: transparent;
    }

    .form-label-group input::-moz-placeholder {
        color: transparent;
    }

    .form-label-group input::placeholder {
        color: transparent;
    }

    .form-label-group input:not(:placeholder-shown) {
        padding-top: calc(var(--input-padding-y) + var(--input-padding-y) * (2 / 3));
        padding-bottom: calc(var(--input-padding-y) / 3);
    }

    .form-label-group input:not(:placeholder-shown)~label {
        padding-top: calc(var(--input-padding-y) / 3);
        padding-bottom: calc(var(--input-padding-y) / 3);
        font-size: 12px;
        color: #777;
    }

    /* Fallback for Edge
-------------------------------------------------- */

    @supports (-ms-ime-align: auto) {
        .form-label-group>label {
            display: none;
        }

        .form-label-group input::-ms-input-placeholder {
            color: #777;
        }
    }

    /* Fallback for IE
-------------------------------------------------- */

    @media all and (-ms-high-contrast: none),
    (-ms-high-contrast: active) {
        .form-label-group>label {
            display: none;
        }

        .form-label-group input:-ms-input-placeholder {
            color: #777;
        }
    }
</style>
{% endblock style %}

{% block body %}
{% include 'navigation.html' %}
{% comment %} event object here {% endcomment %}
<div class="container">
    <div class="row">
      <div class="col-sm-9 col-md-7 col-lg-9 mx-auto">
        <div class="card card-signin my-5">
          <div class="card-body">
            <h5 class="card-title">{{ event.nama_event }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">{{ event.jadwal|date:"l, d/m/Y H:i" }}</h6>
            <h6 class="card-subtitle mb-2 text-muted">Organized by: {{ event.penyelenggara }}</h6>
            <p class="card-text mt-2 mb-2">{{ event.details|linebreaks }}</p>
            <h5>Peserta:</h5>
            <ul>
            {% for attendee in event.peserta.all %}
                <li>{{ attendee }}</li>
            {% endfor %}
            </ul>

            {% if disable %}
            <button href="#" class="btn btn-success" aria-disabled="true" disabled>You joined this event</button>
            {% else %}
            <a href={% url 'eventcatalog:join' event.id %} class="btn btn-success">Join Event</a>
            {% endif %}
            <a href={% url 'eventcatalog:index' %} class="btn">Back to Events</a>
            
          </div>
        </div>
        {% if join and join_success %}
        <div class="alert alert-success">
            <strong>Successfully joined this event!</strong>
        </div>
        {% endif %}
      </div>
    </div>
  </div>
{% endblock body %}

    {% block script_foot %}
    {% comment %} JS to change title according to event title {% endcomment %}
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous">
    </script>
    {% endblock script_foot %}

mainpage/templates/mainpage-index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>TEMU - Discover events around you</title>
<meta name="description" content="Discover events around you">

<meta property="og:title" content="TEMU">
<meta property="og:type" content="website">
<meta property="og:site_name" content="TEMU">
{% endblock head %}

{% block script_head %}
<script src="https://kit.fontawesome.com/31c83bd84a.js" crossorigin="anonymous"></script>
{% endblock script_head %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/normalize.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/layout.css' %}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
{% endblock style %}

{% block body %}
{% include "navigation.html" %}
Hello
{% endblock body %}

{% block script_foot %}
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
{% endblock script_foot %}

mainpage/templates/user-login-gate.html
{% extends 'base.html' %}

{% block head %}
<title>TEMU - Discover events around you</title>
<meta name="description" content="Discover events around you">

<meta property="og:title" content="TEMU">
<meta property="og:type" content="website">
<meta property="og:site_name" content="TEMU">
{% endblock head %}

{% block body %}
{% include 'navigation.html' %}
{% include 'footer.html' %}
{% endblock body %}

mainpage/templates/user-login.html
{% extends 'base.html' %}

{% block head %}
<title>TEMU - Discover events around you</title>
<meta name="description" content="Discover events around you">

<meta property="og:title" content="TEMU">
<meta property="og:type" content="website">
<meta property="og:site_name" content="TEMU">
{% endblock head %}

{% block body %}
{% include 'navigation.html' %}
{% include 'footer.html' %}
{% endblock body %}

templates/base.html
<!DOCTYPE html>

{% load static %}

<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% block head %}
        {% endblock head %}

        {% block script_head %}
        {% endblock script_head %}

        {% block style %}
        {% endblock style %}
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

        {% block body %}
        <div class="navigation">
                {% include 'navigation.html' %}
            </div>
        <div id="page-container">
            <div id="content-wrap">
                {% block content %}
                {% endblock content %}
            </div>
            {% include 'footer.html' %}
        </div>
        {% endblock body %}
        
        {% block script_foot %}
        {% endblock script_foot %}
    </body>
</html>

templates/navigation.html
<style>
@import url('https://fonts.googleapis.com/css2?family=Lemon&display=swap');

.navbar-nav > li{
  margin-left: 8px;
  margin-right: 8px;
}

.navbar-brand {
  font-family: Lemon, cursive;
  font-size: 35px;
  color: #FF6D1C !important;
  text-transform: uppercase;
	text-rendering: optimizeLegibility;
}
</style>

<nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark ">
  <a class="navbar-brand" href={% url 'mainpage:index' %}>Temu</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link active" href={% url 'eventcatalog:index' %}>Events</a>
      </li>
      <li>
        <a class="nav-link active" href={% url 'category:index' %}>Category</a>
      </li>
      {% if not auth %}
        {% if user and user.is_authenticated %}
        <li class="nav-item">
          <span class="navbar-text active">Hello, {{ user.username }} 👋</span>
        </li>
        <li>
          <a href={% url 'userauth:logout' %} class="btn btn-danger">Logout</a>
        </li>
        {% else %}
        <li>
          <a href={% url 'userauth:login' %} class="btn btn-success">Login</a>
        </li>
        {% endif %}
      {% endif %}
    </ul>
  </div>
</nav>